---

# A simple playbook to reboot all of the nodes. 
# This can also be done via the command line: "ansible all -m reboot -b"

- hosts: nodes
  become: true
  tasks:

  - name: reboot all nodes
    ansible.builtin.reboot:
